### PR TITLE
Ticket 30 - Removed highlight on the client logos

### LINKED ISSUE #10: If highlighting client item, it puts a highlight thing over the whole client logo. no thank you
When mousing over any part of a client item, it changes the color of the whole client logo. get rid of that

Image

### PR DESCRIPTION
**Pull request by Figgy24-20**
the problem was in lines 70-72 of the css:

70 `.bio-area .single-bio:hover .thumb::before {`
71 `  opacity: .2;`
72 `}`

### CODE REVIEW

**Comment by komali2** [comment]
well done

**Comment by komali2** [comment]
actually, almost. Rip code out, don't comment it out. If we need it in the future, we can look at git history for it.

**Review by komali2 — CHANGES_REQUESTED** [review]
Delete the code, don't comment out

**Comment by Figgy24-20** [comment]
Oh ok, sure. Will do in the future.

**Review by komali2 — APPROVED** [review]

**Pull request merged**
